import numpy as np
'''
請大家在計算value和Q-value的時候請使用shape為(8,3)的array儲存
並且使用下方的格式做對應
state value Q-value_a1 Q-value_a2
S0    ...   ...        ...
S1    ...   ...        ...
S2    ...   ...        ...
T1    ...   ...        ...
S3    ...   ...        ...
S4    ...   ...        ...
T2    ...   ...        ...
T3    ...   ...        ...
'''

# 生成隨機table作為範例
value = np.random.rand(8,3)

# 舉一個例子，取出V(T1)，也就是取出第三列第零行的元素
v_t1 = value[3,0]

# 儲存根據(a)提供的policy計算出的value的array
np.save('value_a.npy',value)

